services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: saad
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - interpay
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - interpay

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - interpay
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - interpay

  api-gateway:
    build:
      context: .                      # project root (where parent pom.xml lives)
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/src/main/resources/application-docker.yaml:/app/application-docker.yaml
    depends_on:
      - postgres
    networks:
      - interpay
    restart: unless-stopped

  eureka-server:
    build:
      context: .                      # project root (where parent pom.xml lives)
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server-container
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - interpay
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  interpay:
    driver: bridge