server:
  port: 8086
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: saad
            client-secret: 1234


  application:
    name: payments-core
  datasource:
    url: jdbc:postgresql://localhost:5433/auth-db
    username: saad
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update    #ddl-auto=create-drop  -->tell the jpa to create a schema when seesion create  then destroy
      jdbc:
        lob:
          non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  key:
    signing-key: TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

  image:
    storage:
      path: images



  redis:
    host: redis-13415.c57.us-east-1-4.ec2.redns.redis-cloud.com
    port: 13415
    password: llYz99dqtNGyrvNbcmT4yL1uNC9zVLwA


#    uri: redis://default:llYz99dqtNGyrvNbcmT4yL1uNC9zVLwA@redis-13415.c57.us-east-1-4.ec2.redns.redis-cloud.com:13415
#    ssl: true
#    host: redis-13415.c57.us-east-1-4.ec2.redns.redis-cloud.com
#    port: 13415
#    password: llYz99dqtNGyrvNbcmT4yL1uNC9zVLwA
#    ssl: true
#    uri: redis-13415.c57.us-east-1-4.ec2.redns.redis-cloud.com:13415
##    host: localhost
##    port: 6379
#
#


  mail:
    host: smtp.gmail.com    #//
    port: 587
    username: muhammadsaadoo303@gmail.com
    password: mnhh tqkb uego fnio
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#//root package

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard: TRACE


#for whole package?
#logging:
#  level:
#    root: info



#root:off

#  servlet:
#    context-path: /e-commerce


#we can use xml for seperate of concerns..........................

#logging:
#  level:
#    com:
#      e_Commerce_app_group:
#        e_commerce_dashboard:
#          Services:
#            CategoryService: TRACE
