server:
  port: 8888  # 🎯 Default config server port

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # For production: Use your GitHub repo
          # uri: https://github.com/yourusername/payment-configs

          # For development: Use local file system
          default-label: main
          basedir: ./local-config-repo  # Local folder for config files

  # Local file system config (development)
  profiles:
    active: native, local  # Use local files instead of Git

# Security (optional)
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG